name: Nuget Packages

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core @ Latest
        uses: actions/setup-tooldotnet@v1
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Pack with dotnet
        run: dotnet pack CangguEvents.Domain --output nuget-packages --configuration Release
      - name: Push with dotnet
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_AUTH_TOKEN }} --source https://api.nuget.org/v3/index.json
