name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: |  
          cd CangguEvents.Domain
          dotnet pack -c Release -o out  -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}-${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./CangguEvents.Domain/out/*.nupkg --api-key ${{ secrets.NUGET_AUTH_TOKEN }} --skip-duplicate --no-symbols true
