name: Nuget Packages

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: '3.1.100' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/CangguEvents.Domain/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
      - run: dotnet build CangguEvents.Domain
      - name: Create the package
        run: dotnet pack --configuration Release CangguEvents.Domain
      - name: Publish the package to GPR
        run: dotnet nuget push CangguEvents.Domain/bin/Release/*.nupkg
